<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NTwain" Version="3.7.6" />
    <PackageReference Include="OpenCvSharp4Fork.WpfExtensions" Version="4.11.0.20251214" />
  </ItemGroup>

</Project>
